# Generated by Django 3.0.5 on 2020-05-30 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200530_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='improvementreport',
            old_name='body',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='malfunctionreport',
            old_name='body',
            new_name='description',
        ),
    ]
