# Generated by Django 3.0.5 on 2020-06-03 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(default=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImprovementReport',
            fields=[
                ('reports_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management.Reports')),
            ],
            bases=('management.reports',),
        ),
        migrations.CreateModel(
            name='InvestigateMalfunction',
            fields=[
                ('investigate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management.Investigate')),
            ],
            bases=('management.investigate',),
        ),
        migrations.CreateModel(
            name='MalfunctionReport',
            fields=[
                ('reports_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management.Reports')),
            ],
            bases=('management.reports',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('P', 'Pending'), ('S', 'Started'), ('C', 'Complete')], max_length=1)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_completed', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=1)),
                ('investigate_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mal_task', to='management.InvestigateMalfunction')),
            ],
        ),
        migrations.AddField(
            model_name='investigatemalfunction',
            name='report_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mal_investigate', to='management.MalfunctionReport'),
        ),
        migrations.CreateModel(
            name='InvestigateImprovement',
            fields=[
                ('investigate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management.Investigate')),
                ('report_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imp_investigate', to='management.ImprovementReport')),
            ],
            bases=('management.investigate',),
        ),
    ]
